version: "3"
services:
  app:
    container_name: checkrunner-app
    image: 200605030904/checkrunner
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: root

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    restart: always